CREATE TYPE ENUM_LEVEL AS ENUM
    (
        'Trainee',
        'Junior',
        'Middle',
        'Senior'
        );

CREATE TABLE worker
(
    worker_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    birthday DATE,
    level ENUM_LEVEL NOT NULL,
    salary NUMERIC NOT NULL
    CONSTRAINT worker_name_length CHECK (length(name) >= 2 AND length(name) <= 1000),
    CONSTRAINT year_minimum CHECK (birthday > '1900-12-31'),
    CONSTRAINT salary_limit CHECK (salary >= 100 AND salary <= 100000)
);

CREATE TABLE client
(
    client_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
    CONSTRAINT client_name_length CHECK (length(name) >= 2 AND length(name) <= 1000)
);

CREATE TABLE project
(
    project_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INT,
    start_date DATE,
    finish_date DATE,
    CONSTRAINT client_id_fk FOREIGN KEY (client_id) REFERENCES client(client_id)
);

CREATE TABLE project_worker
(
    project_id INT NOT NULL,
    worker_id INT NOT NULL,
    PRIMARY KEY (project_id, worker_id),
    FOREIGN KEY (project_id) REFERENCES project(project_id),
    FOREIGN KEY (worker_id) REFERENCES worker(worker_id)
)


